### PR TITLE
Added proxy config support

### PR DESCRIPTION
**Pull request by nullziu**
Added application level proxy configuration support.
So you can setup your proxy in the config.yml and use it with Buzz. 

```
sensio_buzz:
    proxy: proxy.example.com:8080
```

### CODE REVIEW

**Comment by Isinlor** [comment]
+1

**Comment by marcw** [comment]
I'm not a maintainer of this bundle anymore. Please check with @fabpot, or @lyrixx.

**Comment by lyrixx** [comment]
:+1:

**Comment by Isinlor** [comment]
Thanks for fast reaction! :)

**Pull request merged**
